CREATE TABLE [ard].[DRUG_PRODUCT_INGREDIENTS]
(
	[DRUG_PRODUCT_INGREDIENT_ID] NCHAR(15) NOT NULL PRIMARY KEY, 
    [DRUG_PRODUCT_ID] NCHAR(8) NULL, 
    [DRUGNAME] NVARCHAR(300) NULL, 
    [ACTIVE_INGREDIENT_ID] NCHAR(8) NULL, 
    [ACTIVE_INGREDIENT_NAME] NCHAR(200) NULL
)
