CREATE TABLE [ard].[REACTIONS]
(
	[REACTION_ID] NCHAR(15) NOT NULL PRIMARY KEY, 
    [REPORT_ID] NCHAR(9) NULL, 
    [DURATION_CHAR] NVARCHAR(15) NULL, 
	[DURATION]  AS	CAST([DURATION_CHAR] AS NUMERIC(9,3)),
    [DURATION_UNIT_ENG] NVARCHAR(60) NULL, 
    [DURATION_UNIT_FR] NVARCHAR(60) NULL, 
    [PT_NAME_ENG] NVARCHAR(250) NULL, 
    [PT_NAME_FR] NVARCHAR(250) NULL, 
    [SOC_NAME_ENG] NVARCHAR(250) NULL, 
    [SOC_NAME_FR] NVARCHAR(250) NULL, 
    [MEDDRA_VERSION] NCHAR(9) NULL
)
