CREATE TABLE [dpd].[QRYM_COMPANIES] (
    [DRUG_CODE]                 NCHAR (8)     NOT NULL,
    [MFR_CODE]                  NVARCHAR (5)  NULL,
    [COMPANY_CODE]              NCHAR (6)     NULL,
    [COMPANY_NAME]              NVARCHAR (80) NULL,
    [COMPANY_TYPE]              NVARCHAR (40) NULL,
    [ADDRESS_MAILING_FLAG]      NVARCHAR (1)  NULL,
    [ADDRESS_BILLING_FLAG]      NVARCHAR (1)  NULL,
    [ADDRESS_NOTIFICATION_FLAG] NVARCHAR (1)  NULL,
    [ADDRESS_OTHER]             NVARCHAR (1)  NULL,
    [SUITE_NUMBER]              NVARCHAR (20) NULL,
    [STREET_NAME]               NVARCHAR (80) NULL,
    [CITY_NAME]                 NVARCHAR (60) NULL,
    [PROVINCE]                  NVARCHAR (40) NULL,
    [COUNTRY]                   NVARCHAR (40) NULL,
    [POSTAL_CODE]               NVARCHAR (20) NULL,
    [POST_OFFICE_BOX]           NVARCHAR (15) NULL,
    CONSTRAINT [CK_QRYM_COMPANIES_COMPANY_CODE] CHECK (NOT [COMPANY_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [CK_QRYM_COMPANIES_DRUG_CODE] CHECK (NOT [DRUG_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [FK_QRYM_COMPANIES_QRYM_DRUG_PRODUCT] FOREIGN KEY ([DRUG_CODE]) REFERENCES [dpd].[QRYM_DRUG_PRODUCT] ([DRUG_CODE])
);

