CREATE TABLE [dpd].[QRYM_SCHEDULE] (
    [DRUG_CODE] NCHAR (8)     NOT NULL,
    [SCHEDULE]  NVARCHAR (40) NULL,
    CONSTRAINT [CK_QRYM_SCHEDULE_DRUG_CODE] CHECK (NOT [DRUG_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [FK_QRYM_SCHEDULE_QRYM_DRUG_PRODUCT] FOREIGN KEY ([DRUG_CODE]) REFERENCES [dpd].[QRYM_DRUG_PRODUCT] ([DRUG_CODE])
);

