CREATE TABLE [dpd].[QRYM_PHARMACEUTICAL_STD] (
    [DRUG_CODE]          NCHAR (8)     NOT NULL,
    [PHARMACEUTICAL_STD] NVARCHAR (40) NULL,
    CONSTRAINT [CK_QRYM_PHARMACEUTICAL_STD_DRUG_CODE] CHECK (NOT [DRUG_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [FK_QRYM_PHARMACEUTICAL_STD_QRYM_DRUG_PRODUCT] FOREIGN KEY ([DRUG_CODE]) REFERENCES [dpd].[QRYM_DRUG_PRODUCT] ([DRUG_CODE])
);

