CREATE TABLE [dpd].[QRYM_PACKAGING] (
    [DRUG_CODE]           NCHAR (8)     NOT NULL,
    [UPC]                 NVARCHAR (12) NULL,
    [PACKAGE_SIZE_UNIT]   NVARCHAR (40) NULL,
    [PACKAGE_TYPE]        NVARCHAR (40) NULL,
    [PACKAGE_SIZE]        NVARCHAR (5)  NULL,
    [PRODUCT_INFORMATION] NVARCHAR (80) NULL,
    CONSTRAINT [CK_QRYM_PACKAGING_DRUG_CODE] CHECK (NOT [DRUG_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [FK_QRYM_PACKAGING_QRYM_DRUG_PRODUCT] FOREIGN KEY ([DRUG_CODE]) REFERENCES [dpd].[QRYM_DRUG_PRODUCT] ([DRUG_CODE])
);

