CREATE TABLE [dpd].[QRYM_STATUS] (
    [DRUG_CODE]           NCHAR (8)     NOT NULL,
    [CURRENT_STATUS_FLAG] NVARCHAR (1)  NULL,
    [STATUS]              NVARCHAR (40) NULL,
    [HISTORY_DATE]        AS            (CONVERT([date],[HISTORY_DATE_CHAR],0)),
    [HISTORY_DATE_CHAR]   NVARCHAR (11) NULL,
    CONSTRAINT [CK_QRYM_STATUS_DRUG_CODE] CHECK (NOT [DRUG_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [FK_QRYM_STATUS_QRYM_DRUG_PRODUCT] FOREIGN KEY ([DRUG_CODE]) REFERENCES [dpd].[QRYM_DRUG_PRODUCT] ([DRUG_CODE])
);

