CREATE TABLE [dpd].[QRYM_FORM] (
    [DRUG_CODE]           NCHAR (8)     NOT NULL,
    [PHARM_FORM_CODE]     NCHAR (7)     NULL,
    [PHARMACEUTICAL_FORM] NVARCHAR (40) NULL,
    CONSTRAINT [CK_QRYM_FORM_DRUG_CODE] CHECK (NOT [DRUG_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [CK_QRYM_FORM_PHARM_FORM_CODE] CHECK (NOT [PHARM_FORM_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [FK_QRYM_FORM_QRYM_DRUG_PRODUCT] FOREIGN KEY ([DRUG_CODE]) REFERENCES [dpd].[QRYM_DRUG_PRODUCT] ([DRUG_CODE])
);

