CREATE TABLE [dpd].[QRYM_VETERINARY_SPECIES] (
    [DRUG_CODE]       NCHAR (8)     NOT NULL,
    [VET_SPECIES]     NVARCHAR (80) NULL,
    [VET_SUB_SPECIES] NVARCHAR (80) NULL,
    CONSTRAINT [CK_QRYM_VETERINARY_SPECIES_DRUG_CODE] CHECK (NOT [DRUG_CODE] like '%[^0-9 ]%'),
    CONSTRAINT [FK_QRYM_VETERINARY_SPECIES_QRYM_DRUG_PRODUCT] FOREIGN KEY ([DRUG_CODE]) REFERENCES [dpd].[QRYM_DRUG_PRODUCT] ([DRUG_CODE])
);

