CREATE VIEW [dpd].[loadvw_QRYM_ACTIVE_INGREDIENTS]
	AS 
SELECT
    [DRUG_CODE]              
    ,[ACTIVE_INGREDIENT_CODE]
	,[INGREDIENT]             
	,[INGREDIENT_SUPPLIED_IND]
	,[STRENGTH_CHAR]
	,[STRENGTH_UNIT]
	,[STRENGTH_TYPE]
	,[DOSAGE_VALUE]
	,[BASE]
	,[DOSAGE_UNIT]
	,[NOTES]
FROM QRYM_ACTIVE_INGREDIENTS

