-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE ard.usp_ARD_DATA_LOAD_ALL 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @sql nvarchar(1024);
	DECLARE @dir nvarchar(1024);

	SELECT @dir = DataDir 
	FROM [control].[ControlTable]

	DECLARE curLoadList CURSOR 
	FOR

	
	SELECT 'INSERT INTO ' + ObjectName + ' ' +
		'SELECT A.* FROM OPENROWSET( 
		 BULK ''' + @dir + '\DATA\' + DataFile + ''',
		 FORMATFILE = ''' + @dir + '\FORMAT\' + FormatFile + ''',
	     FIRSTROW = 1
		) AS A'
	FROM [control].[LoadList]
	
	OPEN curLoadList
	FETCH NEXT FROM curLoadList INTO @sql

	WHILE @@FETCH_STATUS = 0   
    BEGIN   
		EXEC (@sql)
		FETCH NEXT FROM curLoadList INTO @sql
	END

	CLOSE curLoadList   
	DEALLOCATE curLoadList

	UPDATE [control].[ControlTable]
	SET DateLoaded = GETDATE()
	/*
	SELECT @sql = '
		INSERT INTO [DPD].[LOADVW_QRYM_DRUG_PRODUCT]
		SELECT A.* FROM OPENROWSET(
		BULK ''' + @dir +'\DATA\DRUG.TXT'',  
		FORMATFILE = ''' + @dir + '\FORMAT\DRUG.FMT'',
		FIRSTROW = 1
		) AS A'
	EXEC @sql



		INSERT INTO [DPD].[QRYM_ACTIVE_INGREDIENTS]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\INGRED.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\INGRED.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_COMPANIES]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\COMP.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\COMP.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[LOADVW_QRYM_STATUS]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\STATUS.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\STATUS.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_FORM]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORM.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\FORM.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_PACKAGING]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\PACKAGE.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\PACKAGE.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_PHARMACEUTICAL_STD]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\PHARM.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\PHARM.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_ROUTE]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\ROUTE.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\ROUTE.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_SCHEDULE]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\SCHEDULE.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\SCHEDULE.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_THERAPEUTIC_CLASS]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\THER.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\THER.FMT',
		FIRSTROW = 1
		) AS A

		INSERT INTO [DPD].[QRYM_VETERINARY_SPECIES]
		SELECT A.* FROM OPENROWSET(
		BULK 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\VET.TXT',
		FORMATFILE = 'E:\PERSONAL\ONEDRIVE\PROJECTS\SAMPLE_DATABASES\DPD_MARKETED\FORMAT\VET.FMT',
		FIRSTROW = 1
		) AS A
*/
END